# Generated by Django 4.1.5 on 2023-01-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
