# Generated by Django 4.1.5 on 2023-01-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
