# Generated by Django 4.1.5 on 2023-01-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Say something about yourself!', max_length=255),
        ),
    ]
