# Generated by Django 4.1.5 on 2023-01-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_room_description_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
