# Generated by Django 4.1.5 on 2023-01-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(default='Chat group just for fun...', max_length=255),
        ),
    ]
