# Generated by Django 4.1.5 on 2023-01-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='images/profile/'),
        ),
    ]
