# Generated by Django 4.1.5 on 2023-06-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/chatroom/'),
        ),
    ]
