# Generated by Django 4.1.5 on 2023-06-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
