# Generated by Django 4.1.5 on 2023-06-20 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0015_remove_message_image_alter_message_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='images/chatroom/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomimages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
