# Generated by Django 4.1.5 on 2023-01-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_personalchat_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalmessage',
            name='chat',
        ),
        migrations.AddField(
            model_name='personalchat',
            name='chat_messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.personalmessage'),
        ),
    ]
