# Generated by Django 4.1.5 on 2023-01-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_personalmessage_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalchat',
            name='chat_messages',
        ),
        migrations.RemoveField(
            model_name='personalchat',
            name='user',
        ),
        migrations.AddField(
            model_name='personalchat',
            name='slug',
            field=models.SlugField(default='-', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalmessages', to='chat.personalchat'),
        ),
        migrations.AlterField(
            model_name='personalchat',
            name='chat_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
