# Generated by Django 4.1.5 on 2023-01-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_personalchat_chat_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmessage',
            name='chat_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
