# Generated by Django 4.1.5 on 2023-01-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_personalmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalchat',
            name='chat_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalmessage',
            name='chat_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
